package com.example.dda_v1

import android.content.Context
import android.os.Environment
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.navigation.NavController
import com.google.firebase.Timestamp
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.launch
import java.io.File
import java.io.FileWriter
import java.util.*
import kotlinx.coroutines.tasks.await
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.rememberScrollState
import android.widget.Toast

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DownloadReportScreen(navController: NavController) {

    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()
    val db = FirebaseFirestore.getInstance()

    val startDateState = rememberDatePickerState()
    val endDateState = rememberDatePickerState()

    var reportGenerated by remember { mutableStateOf(false) }
    val scrollState = rememberScrollState()

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Download Monthly Report") }
            )
        }
    ) { padding ->

        Column(
            modifier = Modifier
                .padding(padding)
                .padding(16.dp)
                .verticalScroll(scrollState)
                .fillMaxSize(),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(24.dp)
        ) {

            //Text("Select Start Date", fontWeight = FontWeight.Bold)
            DatePicker(state = startDateState)

            //Text("Select End Date", fontWeight = FontWeight.Bold)
            DatePicker(state = endDateState)

            Button(
                onClick = {
                    coroutineScope.launch {
                        generateReport(
                            context = context,
                            db = db,
                            startMillis = startDateState.selectedDateMillis,
                            endMillis = endDateState.selectedDateMillis
                        )
                        reportGenerated = true
                    }
                },
                modifier = Modifier.fillMaxWidth()
            ) {
                Text("Download Report")
            }

            if (reportGenerated) {
                Text("Report downloaded in Downloads folder.", color = MaterialTheme.colorScheme.primary)
                navController.navigate("admin_dashboard") {
                    popUpTo("download_report") { inclusive = true }
                }
            }
        }
    }
}

suspend fun generateReport(
    context: Context,
    db: FirebaseFirestore,
    startMillis: Long?,
    endMillis: Long?
) {
    try {

        if (startMillis == null || endMillis == null) {
            Toast.makeText(context, "Please select both dates!", Toast.LENGTH_SHORT).show()
            return
        }

        val startTimestamp = Timestamp(Date(startMillis))
        val endTimestamp = Timestamp(Date(endMillis))

        val snapshot = db.collection("user_details")
            .whereGreaterThanOrEqualTo("timestamp", startTimestamp)
            .whereLessThanOrEqualTo("timestamp", endTimestamp)
            .get()
            .await()

        if (snapshot.isEmpty) {
            Toast.makeText(context, "No data found for selected dates", Toast.LENGTH_LONG).show()
            return
        }

        val users = snapshot.documents.map {
            Triple(
                it.getString("username") ?: "",
                it.getString("email") ?: "",
                it.getString("phone_number") ?: ""
            )
        }

        val csvFile = createCSVFile(context, users)
        //downloadFile(context, csvFile)
        saveFileToDownloads(context, csvFile)

    } catch (e: Exception) {
        e.printStackTrace()
        Toast.makeText(context, "Failed: ${e.message}", Toast.LENGTH_LONG).show()
    }
}

fun createCSVFile(context: Context, users: List<Triple<String, String, String>>): File {
    val file = File(context.getExternalFilesDir(null), "user_report.csv")
    val writer = FileWriter(file)

    writer.append("Username,Email,Phone\n")

    for ((name, email, phone) in users) {
        writer.append("$name,$email,$phone\n")
    }

    writer.flush()
    writer.close()

    return file
}

fun saveFileToDownloads(context: Context, file: File) {
    val downloads = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)

    val targetFile = File(downloads, file.name)

    file.copyTo(targetFile, overwrite = true)

    Toast.makeText(context, "Report saved to Downloads!", Toast.LENGTH_LONG).show()
}